### ISSUE TITLE
Uable to install OSX 10.11.6

### ISSUE THREAD

**Issue by schander** [mdeltito/node-csafe#1]
Hi I have cloned the git repository. Then I try to install using:
`npm install --save csafe`
I get the following error:
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "csafe"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install csafe as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXX/code/node-csafe/npm-debug.log
```
I have attached the npm-debug.log
[npm-debug.log.zip](https://github.com/mdeltito/node-csafe/files/690898/npm-debug.log.zip)

**Comment by mdeltito** [comment]
Hi @schander, thanks for your detailed report. This actually seems to be a slight misunderstanding of the process for installing node packages, rather than an OSX-specific bug.

When downloading/installing a package for nodejs, you can *either* clone the repository, or you can install from npm (npm being the preferred and best-practice approach for most cases). Here, you are trying to install `csafe` inside of itself, which leads to the error you are seeing:

`npm ERR! Refusing to install csafe as a dependency of itself`

Instead you should be creating your own project directory, and then installing csafe into your project. The [npm documentation](https://docs.npmjs.com/getting-started/what-is-npm) will do a much better job of explaining this than I can do here, but a quick example would be:

```bash
$ mkdir schanders-project && cd schanders-project
$ npm init  #this will initialize your project, follow the prompts
$ npm install --save csafe
```

Hope this helps!
